; ESP32 Node-2 — APSTA: kết nối Node-1 lấy file, rồi phát AP "ESP32-Node-2"
[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
upload_port = COM11
monitor_port = COM11
monitor_speed = 115200
upload_speed = 115200
board_build.partitions = no_ota.csv
build_type = release
extra_scripts = post:../strip_symbols.py
build_flags =
    -DBOARD_NODE=1
    -DPHANTOM_DEBUG=0
    ; --- Compiler hardening ---
    -fvisibility=hidden
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -fno-exceptions
    -fstack-protector-strong
    -D_FORTIFY_SOURCE=2
    -O2
    -fomit-frame-pointer
    ; --- Strip debug info ---
    -g0
    -DNDEBUG
