; ESP32 Node-1 — AP_STA: phát AP "ESP32-Node-1", nhận upload từ laptop, sync 2 chiều với Node-2
[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
upload_port = COM9
monitor_port = COM9
monitor_speed = 115200
board_build.partitions = no_ota.csv
build_flags =
    -DBOARD_NODE=1
