; ESP32 Node-1 — AP_STA: phát AP "ESP32-Node-1", nhận upload từ laptop, sync 2 chiều với Node-2
[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
upload_port = COM15
monitor_port = COM15
monitor_speed = 115200
board_build.partitions = no_ota.csv
build_type = release
extra_scripts = post:../strip_symbols.py
build_flags =
    -DBOARD_NODE=2
    -DPHANTOM_DEBUG=0
    ; --- Compiler hardening ---
    -fvisibility=hidden
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -fno-exceptions
    -fstack-protector-strong
    -D_FORTIFY_SOURCE=2
    -O2
    -fomit-frame-pointer
    ; --- Strip debug info ---
    -g0
    -DNDEBUG
