[env:esp32-c6-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino

upload_port = COM6
monitor_port = COM6
monitor_speed = 115200
upload_speed = 460800

board_build.flash_size = 8MB

lib_deps =
    adafruit/Adafruit NeoPixel