; HW Scan firmware — phát hiện thiết bị ngoại vi đang gắn vào ESP32
[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
upload_port = COM12
monitor_port = COM12
monitor_speed = 115200
