[platformio]
default_envs = esp32s3_manual_boot

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 115200
upload_protocol = esptool

upload_flags =
  --before
  default_reset
  --after
  hard_reset
  --connect-attempts
  20

build_unflags =
  -D ARDUINO_USB_MODE=0

build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1

monitor_dtr = 0
monitor_rts = 0

upload_port = COM7
monitor_port = COM7

[env:esp32s3_manual_boot]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 115200
upload_protocol = esptool

upload_flags =
  --before
  no_reset
  --after
  no_reset
  --connect-attempts
  20

build_unflags =
  -D ARDUINO_USB_MODE=0

build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1

monitor_dtr = 0
monitor_rts = 0

upload_port = COM7
monitor_port = COM7

[env:esp32s3_usb_reset]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 115200
upload_protocol = esptool

upload_flags =
  --before
  usb_reset
  --after
  hard_reset
  --connect-attempts
  20

build_unflags =
  -D ARDUINO_USB_MODE=0

build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1

monitor_dtr = 0
monitor_rts = 0

upload_port = COM7
monitor_port = COM7